name: "validate-codeowners"
on:
  pull_request:

jobs:
  validate-codeowners:
    uses: cloudposse/github-action-validate-codeowners/.github/workflows/validate-codeowners-reusable.yml@adding_auto-release
    secrets:
      token: ${{ secrets.CODEOWNERS_VALIDATOR_TOKEN_PUBLIC }}
