name: "validate-codeowners"
on:
  pull_request_target:

jobs:
  validate-codeowners:
    runs-on: ubuntu-latest
    steps:
    - uses: cloudposse/github-action-validate-codeowners/.github/workflows/validate-codeowners-reusable.yml@adding_auto-release
      with:
        token: ${{ secrets.CODEOWNERS_VALIDATOR_TOKEN_PUBLIC }}
